### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by leviathan0117** [akozd/tensorflow_yolov3#3]
Traceback (most recent call last):
  File "detect.py", line 106, in <module>
    _main()
  File "detect.py", line 94, in _main
    filtered_boxes = non_max_suppression(boxes, confidence_threshold=0.5,iou_threshold=0.4)
  File "/root/Downloads/tensorflow_yolo_v3/utils/utils.py", line 129, in non_max_suppression
    image_pred = image_pred.reshape(-1, shape[-1])
ValueError: cannot reshape array of size 1111 into shape (85)

What is this error about?

**Comment by olcaybuyan** [comment]
Within the non_max_supression function change lines 127 and 128 as follows:

127:    image_pred = image_pred[non_zero_idxs **[0]** ]
128:    **#** image_pred = image_pred.reshape(-1, shape[-1])

Otherwise the np.reshape can/will fail transforming the image_pred array into the expected shape.

**Comment by leviathan0117** [comment]
Thank you - I will check if it works & will write back)

**Comment by ShivashishJaishy** [comment]
Yes, it works!

**Comment by PatrickGovan** [comment]
So I made the fix, and you were right, it removed that error, but now when I try and run detect.py I am receiving this overflow error:
line 49, in draw_boxes
    cv2.rectangle(original_image, x0y0, x1y1, (255,255,255), 3)
OverflowError: signed integer is less than minimum
I am not too sure as to how I should go about fixing this.
Any and all help is greatly appreciated!
Thank you!
